#!/bin/bash
directory=dist
targetbranch=gh-pages
build_command() {
  npm run build
}

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" != "master" ]; then
  #echo "Only publishes to github pages from master branch"
  exit 1
fi

echo -e "\033[0;32mDeleting old content...\033[0m"
rm -rf $directory

echo -e "\033[0;32mChecking out $targetbranch...\033[0m"
git worktree add $directory $targetbranch

echo -e "\033[0;32mInstalling packages...\033[0m"
npm install

echo -e "\033[0;32mGenerating site...\033[0m"
build_command

echo -e "\033[0;32mDeploying $targetbranch branch...\033[0m"
cd $directory &&
  git add --all &&
  git commit -m "Deploy updates" &&
  git push --no-verify origin $targetbranch

echo -e "\033[0;32mCleaning up...\033[0m"
cd ..
git worktree remove $directory