#!/bin/bash
directory=dist
targetbranch=gh-pages
build_command() {
  npm run build
}
last_commit_msg=$(git log --format=%B -n 1)

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" != "master" ]; then
  echo "Git Hook:only publishes to GitHub Pages from master branch"
  exit 0
fi

echo "Git Hook: publishing to GitHub Pages from master branch..."

echo -e "\033[0;32mDeleting old content...\033[0m"
rm -rf $directory

echo -e "\033[0;32mChecking out $targetbranch...\033[0m"
git worktree add -f $directory $targetbranch &&
  cd $directory &&
  git pull

echo -e "\033[0;32mInstalling packages...\033[0m"
cd ..
npm install

echo -e "\033[0;32mGenerating site...\033[0m"
build_command

echo -e "\033[0;32mDeploying $targetbranch branch...\033[0m"
cd $directory &&
  git add --all &&
  git commit -m $last_commit_msg &&
  git push origin $targetbranch

echo -e "\033[0;32mCleaning up...\033[0m"
cd ..
git worktree remove $directory